GET http://localhost:8084/comp4537/termproject/api/v1/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiamltIiwiaWF0IjoxNjQ4NzY0MTI0fQ.Ql5Nvokt8oaXxox1E7qFyU_nAjeTa6hDPVnHa2yxbbM

###

POST http://localhost:8084/comp4537/termproject/api/v1/login
Content-Type: application/json

{
    "username": "jim"
}

###

GET http://localhost:8084/comp4537/termproject/api/v1/users

###
POST http://localhost:8084/comp4537/termproject/api/v1/users/register 
Content-Type: application/json

{
    "name": "balex", "password": "simpsons123"
}

POST http://localhost:8084/comp4537/termproject/api/v1/users/login
Content-Type: application/json

{
    "name": "balex", "password": "simpsons123"
}